# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/greg/PycharmProjects/tbtray/tbtrayui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(840, 495)
        icon = QtGui.QIcon.fromTheme("thunderbird")
        Form.setWindowIcon(icon)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineedit_defulticon = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineedit_defulticon.setObjectName("lineedit_defulticon")
        self.horizontalLayout_4.addWidget(self.lineedit_defulticon)
        self.toolButton_defaulticon = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_defaulticon.setObjectName("toolButton_defaulticon")
        self.horizontalLayout_4.addWidget(self.toolButton_defaulticon)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineedit_notifyicon = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineedit_notifyicon.setObjectName("lineedit_notifyicon")
        self.horizontalLayout_5.addWidget(self.lineedit_notifyicon)
        self.toolButton_notifyicon = QtWidgets.QToolButton(self.groupBox_3)
        self.toolButton_notifyicon.setObjectName("toolButton_notifyicon")
        self.horizontalLayout_5.addWidget(self.toolButton_notifyicon)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_notifysound = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_notifysound.setObjectName("checkBox_notifysound")
        self.horizontalLayout_8.addWidget(self.checkBox_notifysound)
        self.lineEdit_notifysound = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_notifysound.setObjectName("lineEdit_notifysound")
        self.horizontalLayout_8.addWidget(self.lineEdit_notifysound)
        self.toolButton_notifysound = QtWidgets.QToolButton(self.groupBox_4)
        self.toolButton_notifysound.setObjectName("toolButton_notifysound")
        self.horizontalLayout_8.addWidget(self.toolButton_notifysound)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_popup = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox_popup.setObjectName("checkBox_popup")
        self.horizontalLayout_7.addWidget(self.checkBox_popup)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.spinBox_xpos = QtWidgets.QSpinBox(self.frame_4)
        self.spinBox_xpos.setMinimumSize(QtCore.QSize(99, 0))
        self.spinBox_xpos.setMaximum(10000)
        self.spinBox_xpos.setProperty("value", 1585)
        self.spinBox_xpos.setObjectName("spinBox_xpos")
        self.horizontalLayout_7.addWidget(self.spinBox_xpos)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.spinBox_displaytime = QtWidgets.QSpinBox(self.frame_4)
        self.spinBox_displaytime.setMinimum(1)
        self.spinBox_displaytime.setProperty("value", 10)
        self.spinBox_displaytime.setObjectName("spinBox_displaytime")
        self.horizontalLayout_7.addWidget(self.spinBox_displaytime)
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.horizontalSlider_opacity = QtWidgets.QSlider(self.frame_4)
        self.horizontalSlider_opacity.setMinimumSize(QtCore.QSize(210, 0))
        self.horizontalSlider_opacity.setMaximum(100)
        self.horizontalSlider_opacity.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_opacity.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_opacity.setObjectName("horizontalSlider_opacity")
        self.horizontalLayout_7.addWidget(self.horizontalSlider_opacity)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.tab)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_favicons = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_favicons.setObjectName("checkBox_favicons")
        self.horizontalLayout_10.addWidget(self.checkBox_favicons)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkbox_showcount = QtWidgets.QCheckBox(self.frame_3)
        self.checkbox_showcount.setObjectName("checkbox_showcount")
        self.horizontalLayout_6.addWidget(self.checkbox_showcount)
        self.pushButton_colourpicker = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_colourpicker.setObjectName("pushButton_colourpicker")
        self.horizontalLayout_6.addWidget(self.pushButton_colourpicker)
        self.label_colour = QtWidgets.QLabel(self.frame_3)
        self.label_colour.setObjectName("label_colour")
        self.horizontalLayout_6.addWidget(self.label_colour)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkbox_minimizetotray = QtWidgets.QCheckBox(self.frame_5)
        self.checkbox_minimizetotray.setMinimumSize(QtCore.QSize(0, 0))
        self.checkbox_minimizetotray.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.checkbox_minimizetotray.setObjectName("checkbox_minimizetotray")
        self.horizontalLayout_9.addWidget(self.checkbox_minimizetotray)
        self.verticalLayout_3.addWidget(self.frame_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editline_profilepath = QtWidgets.QLineEdit(self.groupBox)
        self.editline_profilepath.setObjectName("editline_profilepath")
        self.horizontalLayout.addWidget(self.editline_profilepath)
        self.toolButton_profilepath = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_profilepath.setObjectName("toolButton_profilepath")
        self.horizontalLayout.addWidget(self.toolButton_profilepath)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_accountwarrning = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_accountwarrning.setFont(font)
        self.label_accountwarrning.setText("")
        self.label_accountwarrning.setScaledContents(True)
        self.label_accountwarrning.setObjectName("label_accountwarrning")
        self.horizontalLayout_3.addWidget(self.label_accountwarrning)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pushButton_add = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_add.setObjectName("pushButton_add")
        self.horizontalLayout_3.addWidget(self.pushButton_add)
        self.pushButton_remove = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.horizontalLayout_3.addWidget(self.pushButton_remove)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.listWidget = QtWidgets.QListWidget(self.tab_2)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButton_firepopup = QtWidgets.QToolButton(self.frame)
        self.toolButton_firepopup.setStatusTip("")
        self.toolButton_firepopup.setObjectName("toolButton_firepopup")
        self.horizontalLayout_2.addWidget(self.toolButton_firepopup)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.pushButton_ok = QtWidgets.QPushButton(self.frame)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_2.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(self.frame)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TBTray Settings"))
        self.groupBox_2.setTitle(_translate("Form", "Default Icon Path"))
        self.toolButton_defaulticon.setText(_translate("Form", "..."))
        self.groupBox_3.setTitle(_translate("Form", "Notifiy Icon Path"))
        self.toolButton_notifyicon.setText(_translate("Form", "..."))
        self.groupBox_4.setTitle(_translate("Form", "Notify Sound"))
        self.checkBox_notifysound.setText(_translate("Form", "On/Off"))
        self.toolButton_notifysound.setText(_translate("Form", "..."))
        self.checkBox_popup.setText(_translate("Form", "Show Popup"))
        self.label_3.setText(_translate("Form", "     Popup X position"))
        self.spinBox_xpos.setSuffix(_translate("Form", " px"))
        self.label_4.setText(_translate("Form", "   Display Time"))
        self.spinBox_displaytime.setSuffix(_translate("Form", " sec\'s"))
        self.label.setText(_translate("Form", "    Opacity"))
        self.checkBox_favicons.setText(_translate("Form", "Show Mail Favicons"))
        self.checkbox_showcount.setText(_translate("Form", "Show unread Count"))
        self.pushButton_colourpicker.setText(_translate("Form", "Colour Picker"))
        self.label_colour.setText(_translate("Form", "Colour of unread count font"))
        self.checkbox_minimizetotray.setText(_translate("Form", "Minimize to tray"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Genral"))
        self.groupBox.setTitle(_translate("Form", "Profile Path selector"))
        self.toolButton_profilepath.setText(_translate("Form", "..."))
        self.label_2.setText(_translate("Form", "Profile List  ( .msf files)"))
        self.pushButton_add.setText(_translate("Form", "Add"))
        self.pushButton_remove.setText(_translate("Form", "Remove"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Accounts"))
        self.toolButton_firepopup.setToolTip(_translate("Form", "test popup"))
        self.toolButton_firepopup.setText(_translate("Form", "..."))
        self.pushButton_ok.setText(_translate("Form", "OK"))
        self.pushButton_cancel.setText(_translate("Form", "Cancel"))

